# This file was generated by GoReleaser. DO NOT EDIT.
class Github < Formula
  desc "Simple tool to test/debug/diagnose connections to OpenConfig servers"
  homepage "https://github.com/vapor-ware/octool"
  version "0.1.0-rc0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/octool/releases/download/v0.1.0-rc0/octool_0.1.0-rc0_darwin_amd64.tar.gz"
    sha256 "c73467f83e319000789a74d09c3d6d46055098131a94813b2ecfbd2bdb7d63b9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/octool/releases/download/v0.1.0-rc0/octool_0.1.0-rc0_linux_amd64.tar.gz"
      sha256 "a185acc6c7ef2e17f7136e12a855b19c9010c61e8f12d5f1e9f74a373f68c065"
    end
  end

  def install
    bin.install "octool"
  end

  test do
    system "#{bin}/octool -h"
  end
end
