# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Github < Formula
  desc "Manage secrets on Google Cloud Platform with KMS and state files"
  homepage "https://github.com/vapor-ware/sctl"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vapor-ware/sctl/releases/download/1.6.0/sctl_1.6.0_Darwin_arm64.tar.gz"
      sha256 "fb8f0787cada818e6139f8e45ef48604550a9664d3164ccbc98f733152e9442f"

      def install
        bin.install "sctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/sctl/releases/download/1.6.0/sctl_1.6.0_Darwin_x86_64.tar.gz"
      sha256 "e3497bc841cdd14845c911fdfc7d38489b642c8cd32e554896f069cfffb3b393"

      def install
        bin.install "sctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/sctl/releases/download/1.6.0/sctl_1.6.0_Linux_x86_64.tar.gz"
      sha256 "42f0e6e7255ad61a40922f999a9179a2645f1b6b73ad84261207b1ac152cabb0"

      def install
        bin.install "sctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vapor-ware/sctl/releases/download/1.6.0/sctl_1.6.0_Linux_arm64.tar.gz"
      sha256 "7ddc209cda94169cc135134b771528db5e7fc65b3a098360f9834a82ebf97c9c"

      def install
        bin.install "sctl"
      end
    end
  end

  test do
    system "#{bin}/sctl --version"
  end
end
