# This file was generated by GoReleaser. DO NOT EDIT.
class Octool < Formula
  desc "Simple tool to test/debug/diagnose connections to OpenConfig servers"
  homepage "https://github.com/vapor-ware/octool"
  version "0.1.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/octool/releases/download/v0.1.0-rc1/octool_0.1.0-rc1_darwin_amd64.tar.gz"
    sha256 "855066a4d695f8ba931095c4955207904ee851d003af3ff6c96cf3ee4f9241c8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/octool/releases/download/v0.1.0-rc1/octool_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "89f2a04f605eee586d5564774e099ebc1b9203aab89b6ad9dded146cce8649a2"
    end
  end

  def install
    bin.install "octool"
  end

  test do
    system "#{bin}/octool -h"
  end
end
