# This file was generated by GoReleaser. DO NOT EDIT.
class Ouroboros < Formula
  desc "A Helm(file) toolkit designed to flatten the curve for knowledge required to perform deployments at Vapor."
  homepage "https://github.com/vapor-ware/ouroboros"
  version "0.1.0-rc.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/ouroboros/releases/download/0.1.0-rc.3/ouroboros_0.1.0-rc.3_darwin_amd64.tar.gz"
    sha256 "380787579b32123ac4877eb0022a3454b54cd22b7e5f516cabea8fae482f4675"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/ouroboros/releases/download/0.1.0-rc.3/ouroboros_0.1.0-rc.3_linux_amd64.tar.gz"
      sha256 "6a25aea637fa97ea738ce8469f8bd064a37bc939991913cdc6c6c80fef516ddb"
    end
  end

  def install
    bin.install "our"
  end

  test do
    system "#{bin}/our --version"
  end
end
