# This file was generated by GoReleaser. DO NOT EDIT.
class Sctl < Formula
  desc "Manage secrets on Google Cloud Platform with KMS and state files"
  homepage "https://github.com/vapor-ware/sctl"
  version "1.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/sctl/releases/download/1.4.2/sctl_1.4.2_Darwin_x86_64.tar.gz"
    sha256 "df203dec7662de35382dc10a2dab02e4985c9034a558afc4fe7da4b41a535761"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/sctl/releases/download/1.4.2/sctl_1.4.2_Linux_x86_64.tar.gz"
      sha256 "267623fa7e361a10d5a48e2bf29d9402fbbb117b23e2b38ff71129d2ec8eaad5"
    end
  end

  def install
    bin.install "sctl"
  end

  test do
    system "#{bin}/sctl --version"
  end
end
