# This file was generated by GoReleaser. DO NOT EDIT.
class Sctl < Formula
  desc "Manage secrets on Google Cloud Platform with KMS and state files"
  homepage "https://github.com/vapor-ware/sctl"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/sctl/releases/download/1.4.0/sctl_1.4.0_Darwin_x86_64.tar.gz"
    sha256 "29474fe8a20cb757bb763dd165b6ba2bca6d939051e6fae930c04465865fc76a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/sctl/releases/download/1.4.0/sctl_1.4.0_Linux_x86_64.tar.gz"
      sha256 "71d01c5e5614ad6feb830dd1bc1027a776b92834abf7e7c30370f751cbe135ed"
    end
  end

  def install
    bin.install "sctl"
  end

  test do
    system "#{bin}/sctl --version"
  end
end
