# This file was generated by GoReleaser. DO NOT EDIT.
class Synse < Formula
  desc "Unified CLI for Vapor IO's Synse platform."
  homepage "https://github.com/vapor-ware/synse-cli"
  version "3.0.0"

  if OS.mac?
    url "https://github.com/vapor-ware/synse-cli/releases/download/3.0.0/synse_3.0.0_darwin_amd64.tar.gz"
    sha256 "dd00a74375fa32091aa90cf0d1d1caf11e3fa1e7aad9edee046d93febca8e148"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/synse-cli/releases/download/3.0.0/synse_3.0.0_linux_amd64.tar.gz"
      sha256 "0066721a54a57a31d5b38097382256ce5b0d3f12e407d91feccdf18774fb7450"
    end
  end

  def install
    bin.install "synse"
  end

  test do
    system "#{bin}/synse version"
  end
end
