# This file was generated by GoReleaser. DO NOT EDIT.
class Synse < Formula
  desc "Unified CLI for Vapor IO's Synse platform."
  homepage "https://github.com/vapor-ware/synse-cli"
  version "3.0.0-alpha.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vapor-ware/synse-cli/releases/download/3.0.0-alpha.4/synse_3.0.0-alpha.4_darwin_amd64.tar.gz"
    sha256 "608b261560975ab572402ee423c1b06973ed63511357b5ad318051de2b615027"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vapor-ware/synse-cli/releases/download/3.0.0-alpha.4/synse_3.0.0-alpha.4_linux_amd64.tar.gz"
      sha256 "07f4fe19d210e1d69e12c057c9cef2c7af715802a7b89d93e063f4bf075c17da"
    end
  end

  def install
    bin.install "synse"
  end

  test do
    system "#{bin}/synse version"
  end
end
